//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assets.Res {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource2() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assets.Res.Resource2", typeof(Resource2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на earth.
        /// </summary>
        internal static string _0x1 {
            get {
                return ResourceManager.GetString("0x1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на stone.
        /// </summary>
        internal static string _0x2 {
            get {
                return ResourceManager.GetString("0x2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на copper.
        /// </summary>
        internal static string _0x3c {
            get {
                return ResourceManager.GetString("0x3c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на coal.
        /// </summary>
        internal static string _0x3co {
            get {
                return ResourceManager.GetString("0x3co", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на diamonds.
        /// </summary>
        internal static string _0x3d {
            get {
                return ResourceManager.GetString("0x3d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на gold.
        /// </summary>
        internal static string _0x3g {
            get {
                return ResourceManager.GetString("0x3g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на iron.
        /// </summary>
        internal static string _0x3i {
            get {
                return ResourceManager.GetString("0x3i", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на tree.
        /// </summary>
        internal static string _0x4 {
            get {
                return ResourceManager.GetString("0x4", resourceCulture);
            }
        }
    }
}
